### ISSUE TITLE
App doesn't need READ_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by wojtek-kalicinski** [rpandey1234/MyMemory#1]
The external storage permission is not required for getting images from other apps, and in fact it's really bad practice to ask for this permission in most situations. Your memory app doesn't have any features that would require accessing the external storage.
You can check it by commenting out the permission related code and your app works just fine, including creating custom games.

**Comment by rpandey1234** [comment]
I'd like to understand this more. As per https://developer.android.com/training/data-storage, accessing shareable media files like images requires `READ_EXTERNAL_STORAGE`. 

So does `Intent.createChooser(Intent(Intent.ACTION_PICK), "Choose pics")` not provide the ability to get photos stored on external storage (e.g. photos on an SD card)?

**Comment by wojtek-kalicinski** [comment]
The case you describe is when you want to be able to enumerate and read the files using the MediaStore API etc.

In your case, your app does not need access to the list of files, it asks another app (through ACTION_PICK) to provide only the photos the user selects. What you get back are content:// Uri instances where the picker app (e.g. Google Photos) granted your app the permission to acccess those Uris.
In this case it doesn't matter where the photos are, since you never access Files (as in filesystem files) - they can be on storage, they can be in RAM or coming from network, and they are represented only by a Uri handle.

**Comment by rpandey1234** [comment]
Thanks, appreciate the explanation! I addressed this here: https://github.com/rpandey1234/MyMemory/pull/2/commits/030ade193be6b9b3c881b82c34d97b7428ae7541
